---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: "backend"
        image: "{{ .Values.backend_image.name }}:{{ .Values.backend_image.tag }}"
        ports: 
        - containerPort: 8080
        env:
        - name: "PG_HOST"
          value: "10.155.70.3"
        - name: "PG_PORT"
          value: "5432"
        - name: "PG_DB_NAME"
          value: "postgres"
        - name: "PG_USER"
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: username
        - name: "PG_PASS"      
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: password
        - name: "REDIS_HOST"
          value: "localhost"
        - name: "REDIS_PORT"
          value: "6379"
        - name: "MONGO_HOST"
          value: "localhost"
        - name: "MONGO_PORT"
          value: "27017"
        - name: "MONGO_DB_NAME"
          value: "schedule"

      - name: "redis"
        image: "redis:7-alpine"

